# Etapa de construcción
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod tidy
COPY . .
RUN go build -o counterapp
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/counterapp .
ARG PORT=8082
ENV PORT=${PORT}
EXPOSE ${PORT}
CMD ["sh", "-c", "./counterapp"]
