FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod tidy
COPY . .
RUN go build -o myjsonapp
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/myjsonapp .
EXPOSE 8081
CMD ["./myjsonapp"]
